// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateApp.Data;

#nullable disable

namespace RealEstateApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302104859_AddUserIdentityUserTable")]
    partial class AddUserIdentityUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateApp.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgentFirstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentLastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("RealEstateApp.Models.AgentListingCase", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<int>("ListingCaseId")
                        .HasColumnType("integer");

                    b.HasKey("AgentId", "ListingCaseId");

                    b.HasIndex("ListingCaseId");

                    b.ToTable("AgentListingCases");
                });

            modelBuilder.Entity("RealEstateApp.Models.AgentPhotographyCompany", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<string>("PhotographyCompanyId")
                        .HasColumnType("text");

                    b.HasKey("AgentId", "PhotographyCompanyId");

                    b.HasIndex("PhotographyCompanyId");

                    b.ToTable("AgentPhotographyCompanies");
                });

            modelBuilder.Entity("RealEstateApp.Models.CaseContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListingCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("caseContacts");
                });

            modelBuilder.Entity("RealEstateApp.Models.ListingCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FloorArea")
                        .HasColumnType("double precision");

                    b.Property<int>("Garages")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<int>("ListingCaseStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PhotographyCompanyId")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<int>("SaleCategory")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("postcode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotographyCompanyId");

                    b.ToTable("ListingCases");
                });

            modelBuilder.Entity("RealEstateApp.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("ListingCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingCaseId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("RealEstateApp.Models.PhotographyCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PhotographyCompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhotographyCompanies");
                });

            modelBuilder.Entity("RealEstateApp.Models.UserIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserIdentityUsers");
                });

            modelBuilder.Entity("RealEstateApp.Models.AgentListingCase", b =>
                {
                    b.HasOne("RealEstateApp.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateApp.Models.ListingCase", "ListingCase")
                        .WithMany()
                        .HasForeignKey("ListingCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ListingCase");
                });

            modelBuilder.Entity("RealEstateApp.Models.AgentPhotographyCompany", b =>
                {
                    b.HasOne("RealEstateApp.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateApp.Models.PhotographyCompany", "PhotographyCompany")
                        .WithMany()
                        .HasForeignKey("PhotographyCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("PhotographyCompany");
                });

            modelBuilder.Entity("RealEstateApp.Models.ListingCase", b =>
                {
                    b.HasOne("RealEstateApp.Models.PhotographyCompany", "PhotographyCompany")
                        .WithMany()
                        .HasForeignKey("PhotographyCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PhotographyCompany");
                });

            modelBuilder.Entity("RealEstateApp.Models.MediaAsset", b =>
                {
                    b.HasOne("RealEstateApp.Models.ListingCase", "ListingCase")
                        .WithMany()
                        .HasForeignKey("ListingCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListingCase");
                });
#pragma warning restore 612, 618
        }
    }
}
